config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  namespace :admin do
    resources :projects, except: [ :show ]
  end
  
  get :about,   controller: :pages
  get :faq,     controller: :pages
  get :home,    controller: :pages
  get :resume,  controller: :pages
  
  resources :projects, only: [ :index, :show ]
  
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title,
            :image,
            :short_desc,
            :long_desc,
            :project_link, 
            presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admin_controller.rb
class AdminController < ApplicationController
  def redirect_unless_user_is_admin
    unless current_user && current_user.is_admin
      redirect_to root_url, notice: 'You do not have permission to access the requested page.'
    end
  end
end

app/controllers/admin/projects_controller.rb
require 'admin/admin_controller.rb'

class Admin::ProjectsController < AdminController
  before_action :redirect_unless_user_is_admin
  before_action :set_project, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :image, :short_desc, :long_desc, :project_link)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def resume
  end

  def faq
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @projects = Project.all
  end

  def show
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_with(model: project, local: true, url: admin_projects_path) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :project_image %>
  </div>

  <div class="field">
    <%= form.label :short_desc %>
    <%= form.text_field :short_desc, id: :project_short_desc %>
  </div>

  <div class="field">
    <%= form.label :long_desc %>
    <%= form.text_area :long_desc, id: :project_long_desc %>
  </div>

  <div class="field">
    <%= form.label :project_link %>
    <%= form.text_field :project_link, id: :project_project_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/admin/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Short desc</th>
      <th>Long desc</th>
      <th>Project link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.image %></td>
        <td><%= project.short_desc %></td>
        <td><%= project.long_desc %></td>
        <td><%= project.project_link %></td>
        <td><%= link_to 'Show', project, target: :blank %></td>
        <td><%= link_to 'Edit', edit_admin_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_admin_project_path, class: 'btn btn-primary'%>

app/views/admin/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', admin_projects_path %>

app/views/layouts/_footer.html.erb
<div id="full-height">
</div>
<footer id="footer">
  <div class="container">
    <div class="clearfix">
      <ul class="nav navbar-nav">
        <li>
          <a href="#">FAQ</a>
        </li>
        <li>
          <a href="#">FAQ</a>
        </li>
        <li>
          <a href="#">FAQ</a>
        </li>
        <li>
          <a href="#">FAQ</a>
        </li>
        <li>
          <%- if current_user %>
            <%= link_to "logout", destroy_user_session_path, method: :delete %>
          <%- else %>
            <%= link_to "login", new_user_session_path %>
          <%- end %>
        </li>
      </ul>
    </div>
  </div>
</footer>
<script>
var h = window.innerHeight;
var el = document.getElementById("footer");
var oh = el.getBoundingClientRect().top;

var toAdd = h - oh - 50;
toAdd += 'px';
document.getElementById("full-height").style.height = toAdd;
</script>

app/views/layouts/_navbar.html.erb
<div>
  <ul class="nav navbar-nav">
    <li><%=link_to "HOME", root_url %></li>
    <li><%=link_to "ABOUT", about_path%></li>
    <li><%=link_to "PROJECTS", projects_path %></li>
    <li><%=link_to "RESUME", resume_path %></li>
    <li><%=link_to "FAQS", faq_path %></li>
    <li><a href="#">CONTACT</a></li>
    <%- if current_user && current_user.is_admin %>
      <li><%=link_to "Admin", admin_projects_path %></li>
    <%- end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-wrapper">
      <div class="container">
        <div class="clearfix">
          <%= render "layouts/navbar" %>
        </div>
      </div>
    </div>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>I'm an amazing programmer</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat nibh sed pulvinar proin. Praesent elementum facilisis leo vel fringilla. Hac habitasse platea dictumst vestibulum rhoncus. Volutpat est velit egestas dui id ornare arcu. Massa sapien faucibus et molestie ac feugiat sed. Tincidunt augue interdum velit euismod in pellentesque massa. Sit amet porttitor eget dolor morbi non. Vehicula ipsum a arcu cursus vitae congue mauris. Amet justo donec enim diam vulputate ut pharetra sit amet. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Et egestas quis ipsum suspendisse. Amet volutpat consequat mauris nunc congue nisi. A lacus vestibulum sed arcu non odio euismod. Rhoncus urna neque viverra justo nec ultrices dui sapien. Vitae aliquet nec ullamcorper sit amet. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Aliquet lectus proin nibh nisl condimentum id venenatis. Neque vitae tempus quam pellentesque nec nam aliquam sem et.
</p><p>
  Posuere morbi leo urna molestie at elementum. Cras semper auctor neque vitae tempus quam pellentesque nec. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Condimentum id venenatis a condimentum. Tellus at urna condimentum mattis. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Nec ultrices dui sapien eget mi proin sed libero. Consequat mauris nunc congue nisi vitae suscipit tellus. Ut sem viverra aliquet eget sit amet tellus. Amet est placerat in egestas erat imperdiet sed euismod nisi. Est ultricies integer quis auctor elit sed vulputate.
</p><p>
  Scelerisque in dictum non consectetur a erat nam. Dictum varius duis at consectetur. Sed arcu non odio euismod. Lorem sed risus ultricies tristique nulla aliquet enim. Ac turpis egestas maecenas pharetra convallis posuere. Ut eu sem integer vitae justo eget magna fermentum iaculis. Pretium nibh ipsum consequat nisl. Augue lacus viverra vitae congue eu consequat ac. Blandit aliquam etiam erat velit scelerisque in dictum non. Nec sagittis aliquam malesuada bibendum. Urna cursus eget nunc scelerisque viverra.
</p><p>
  Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Amet risus nullam eget felis eget nunc. Duis ut diam quam nulla. Ut tortor pretium viverra suspendisse potenti. Eget duis at tellus at urna condimentum mattis pellentesque id. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Bibendum enim facilisis gravida neque convallis. Et pharetra pharetra massa massa ultricies. Libero justo laoreet sit amet. Vitae turpis massa sed elementum tempus egestas. Proin libero nunc consequat interdum varius. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl.
</p><p>
  Bibendum arcu vitae elementum curabitur. Diam vulputate ut pharetra sit amet aliquam id diam. In nibh mauris cursus mattis molestie a iaculis at erat. Nisi lacus sed viverra tellus in hac habitasse platea. Amet nulla facilisi morbi tempus iaculis urna. Id eu nisl nunc mi ipsum. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Consectetur libero id faucibus nisl tincidunt eget nullam non. In mollis nunc sed id semper risus. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Duis at consectetur lorem donec massa sapien faucibus. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Nulla facilisi nullam vehicula ipsum a. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Laoreet non curabitur gravida arcu ac tortor dignissim. Turpis egestas pretium aenean pharetra magna. Donec massa sapien faucibus et molestie ac feugiat. Id neque aliquam vestibulum morbi blandit cursus risus at. Cursus mattis molestie a iaculis at erat.
</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<h1>Hello, I'm Jesse</h1>
<br />
<p>
  I'm an awesome programmer who can make your dreams come true!
</p>
<p>
  Use the links above to learn how...
</p>

app/views/pages/resume.html.erb
<h1>Resume</h1>
<p>I'm an amazing programmer</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat nibh sed pulvinar proin. Praesent elementum facilisis leo vel fringilla. Hac habitasse platea dictumst vestibulum rhoncus. Volutpat est velit egestas dui id ornare arcu. Massa sapien faucibus et molestie ac feugiat sed. Tincidunt augue interdum velit euismod in pellentesque massa. Sit amet porttitor eget dolor morbi non. Vehicula ipsum a arcu cursus vitae congue mauris. Amet justo donec enim diam vulputate ut pharetra sit amet. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Et egestas quis ipsum suspendisse. Amet volutpat consequat mauris nunc congue nisi. A lacus vestibulum sed arcu non odio euismod. Rhoncus urna neque viverra justo nec ultrices dui sapien. Vitae aliquet nec ullamcorper sit amet. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Aliquet lectus proin nibh nisl condimentum id venenatis. Neque vitae tempus quam pellentesque nec nam aliquam sem et.
</p><p>
  Posuere morbi leo urna molestie at elementum. Cras semper auctor neque vitae tempus quam pellentesque nec. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Condimentum id venenatis a condimentum. Tellus at urna condimentum mattis. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Nec ultrices dui sapien eget mi proin sed libero. Consequat mauris nunc congue nisi vitae suscipit tellus. Ut sem viverra aliquet eget sit amet tellus. Amet est placerat in egestas erat imperdiet sed euismod nisi. Est ultricies integer quis auctor elit sed vulputate.
</p><p>
  Scelerisque in dictum non consectetur a erat nam. Dictum varius duis at consectetur. Sed arcu non odio euismod. Lorem sed risus ultricies tristique nulla aliquet enim. Ac turpis egestas maecenas pharetra convallis posuere. Ut eu sem integer vitae justo eget magna fermentum iaculis. Pretium nibh ipsum consequat nisl. Augue lacus viverra vitae congue eu consequat ac. Blandit aliquam etiam erat velit scelerisque in dictum non. Nec sagittis aliquam malesuada bibendum. Urna cursus eget nunc scelerisque viverra.
</p><p>
  Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Amet risus nullam eget felis eget nunc. Duis ut diam quam nulla. Ut tortor pretium viverra suspendisse potenti. Eget duis at tellus at urna condimentum mattis pellentesque id. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Bibendum enim facilisis gravida neque convallis. Et pharetra pharetra massa massa ultricies. Libero justo laoreet sit amet. Vitae turpis massa sed elementum tempus egestas. Proin libero nunc consequat interdum varius. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl.
</p><p>
  Bibendum arcu vitae elementum curabitur. Diam vulputate ut pharetra sit amet aliquam id diam. In nibh mauris cursus mattis molestie a iaculis at erat. Nisi lacus sed viverra tellus in hac habitasse platea. Amet nulla facilisi morbi tempus iaculis urna. Id eu nisl nunc mi ipsum. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Consectetur libero id faucibus nisl tincidunt eget nullam non. In mollis nunc sed id semper risus. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Duis at consectetur lorem donec massa sapien faucibus. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Nulla facilisi nullam vehicula ipsum a. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Laoreet non curabitur gravida arcu ac tortor dignissim. Turpis egestas pretium aenean pharetra magna. Donec massa sapien faucibus et molestie ac feugiat. Id neque aliquam vestibulum morbi blandit cursus risus at. Cursus mattis molestie a iaculis at erat.
</p>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>
<div class="row">
  <% @projects.each do |project| %>
    <div class="col-sm-4">
      <div class="proj-card">      
        <h3><%= project.title %></h3>
        <%= project.image %>
        <p><%= project.short_desc %></p>
        <%= link_to 'live project', project.project_link %><br />
        <%= link_to 'More info', project %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @project.image %>
</p>

<p>
  <strong>Short desc:</strong>
  <%= @project.short_desc %>
</p>

<p>
  <strong>Long desc:</strong>
  <%= @project.long_desc %>
</p>

<p>
  <strong>Project link:</strong>
  <%= @project.project_link %>
</p>